### Can fit parameters be recovered?
## Use simulated data generated by model in chinook_fit to determine whether key
## parameters can be reliably recovered.
## Sep 29, 2022
## Reran Oct 26: parameters recovered well for most species except range biased 
# high and headrope depth coefficients uncertain for chum in particular;
# consider rerunning with smooth for headrope, not cat. effects
## Reran Jan 31: "final" model after comparing spatiotemporal structures with
# cross validation
## Reran April 3: 


library(tidyverse)
library(sdmTMB)
library(ggplot2)

ncores <- parallel::detectCores() 
future::plan(future::multisession, workers = ncores - 3)


# fitted model from all_species_fit.R
fit_all_sp <- readRDS(
  here::here("data", "fits", "top_st_mod_all_sp_season.rds")) %>% 
  mutate(
    anisotropy = ifelse(species == "chinook" & dataset == "summer", FALSE, TRUE)
  )

  

# simulate 20 MC draws from fitted models 
set.seed(456)
nsims = 20
sims_list <- purrr::map(
  fit_all_sp$fits, simulate, nsim = nsims, re_form = ~0,
)


## for each simulated dataset, refit model, recover pars and store

# make a tibble for each species simulations
sim_tbl <- purrr::pmap(
  list(fit_all_sp$species, fit_all_sp$dataset, fit_all_sp$fits, sims_list),
  function (sp, season, fits, x) {
    tibble(
      species = sp,
      season = season,
      iter = seq(1, nsims, by = 1),
      sim_dat = lapply(seq_len(ncol(x)), function(i) {
        # use fits instead of data in tibble because mismatched
        fits$data %>% 
          mutate(sim_catch = x[ , i])
      })
    )
  }
) %>% 
  bind_rows() %>% 
  left_join(., 
            fit_all_sp %>% select(species, season = dataset, model, anisotropy,
                                  fits), 
            by = c("species", "season"))


# pull meshes from fitted model to use (doesn't work so rebuild)
# fit_all_sp$mesh <- purrr::map(fit_all_sp$st_mod, ~ .x$mesh)
## use INLA mesh based on SA recommendations and model selection (see notes)
dat_coords <- fit_all_sp$data[[1]] %>% 
  select(utm_x_1000, utm_y_1000) %>% 
  as.matrix()
inla_mesh_raw <- INLA::inla.mesh.2d(
  loc = dat_coords,
  max.edge = c(1, 5) * 500,
  cutoff = 20,
  offset = c(20, 200)
) 
spde <- make_mesh(
  fit_all_sp$data[[1]],
  c("utm_x_1000", "utm_y_1000"),
  mesh = inla_mesh_raw
) 



## test w/ single model
dum <- sdmTMB(
  fit_all_sp$fits[[1]]$formula[[1]],
  offset = sim_tbl$sim_dat[[1]]$effort,
  data = sim_tbl$sim_dat[[1]],
  mesh =  fit_all_sp$fits[[1]]$spde,
  family = sdmTMB::nbinom2(),
  spatial = "on",
  spatiotemporal = sim_tbl$model[[1]],
  time = "year",
  share_range = FALSE,
  anisotropy = sim_tbl$anisotropy[[1]],
  control = sdmTMBcontrol(
    # nlminb_loops = 2
    newton_loops = 1
  )
)

sim_tbl$species_season <- paste(sim_tbl$species, sim_tbl$season, sep = "_")
sp_vec <- unique(sim_tbl$species_season)
for (i in seq_along(sp_vec)) {
  sim_tbl_sub <- sim_tbl %>% filter(species_season == sp_vec[i])
  fit <- furrr::future_pmap(
    list(sim_tbl_sub$sim_dat, sim_tbl_sub$fits, sim_tbl_sub$model,
         sim_tbl_sub$anisotropy), 
    function (x, fit, st_model, aniso) {
      sdmTMB(
        fit$formula[[1]],
        offset = x$effort,
        data = x,
        mesh = fit$spde,
        family = sdmTMB::nbinom2(),
        spatial = "on",
        spatiotemporal = st_model,
        time = "year",
        anisotropy = aniso,
        control = sdmTMBcontrol(
          # nlminb_loops = 2
          newton_loops = 1
        )
      )
    },
    .options = furrr::furrr_options(seed = TRUE)
  )
  saveRDS(
    fit,
    here::here("data", "fits", "sim_fit", paste(sp_vec[i], ".rds", sep = ""))
  )
  }


# import saved sim fits 
sim_fit_list <- purrr::map(
  sp_vec,
  ~ readRDS(
    here::here("data", "fits", "sim_fit", paste(.x, ".rds", sep = ""))
  )
)
sim_tbl$sim_fit <- do.call(c, sim_fit_list)


# how many had convergence issues by species?
purrr::map(sim_fit_list, ~ .x$converged) 


# extract fixed and ran effects pars from simulations
sim_tbl$pars <- purrr::map(
  sim_tbl$sim_fit, function (x) {
    fix <- tidy(x, effects = "fixed")
    ran <- tidy(x, effects = "ran_pars")
    rbind(fix, ran) 
  }
)

sim_pars <- sim_tbl %>% 
  select(species, iter, pars) %>% 
  unnest(cols = c(pars)) %>% 
  mutate(iter = as.factor(iter),
         species = abbreviate(species, minlength = 3)) %>% 
  # add unique identifier for second range term
  group_by(iter, species, term) %>% 
  mutate(par_id = row_number(),
         term = ifelse(par_id > 1, paste(term, par_id, sep = "_"), term)) %>% 
  ungroup()
saveRDS(sim_pars, here::here("data", "preds", "sim_pars.rds"))


# as above but for fitted models
fit_effs <- purrr::map2(
  fit_all_sp$st_mod, fit_all_sp$species, function (x, sp) {
    fix <- tidy(x, effects = "fixed")
    ran <- tidy(x, effects = "ran_pars")
    rbind(fix, ran) %>% 
      mutate(species = abbreviate(sp, minlength = 3)) %>% 
      # add unique identifier for second range term
      group_by(species, term) %>% 
      mutate(
        par_id = row_number(),
        term = ifelse(par_id > 1, paste(term, par_id, sep = "_"), term)
      ) %>% 
      ungroup()
  }
) %>% 
  bind_rows() 

sim_box <- ggplot() +
  geom_boxplot(data = sim_pars, aes(x = species, y = estimate)) +
  geom_point(data = fit_effs, aes(x = species, y = estimate), colour = "red") +
  facet_wrap(~term, scales = "free") +
  ggsidekick::theme_sleek()

png(here::here("figs", "ms_figs", "par_recovery_sim_box.png"), 
    height = 7, width = 11, units = "in", res = 250)
sim_box
dev.off()
