### Can fit parameters be recovered?
## Use simulated data generated by model in all_species_fit_season_mvrw to 
## determine whether parameters can be recovered.
## Sep 27, 2023

# setup ---------------------------------------------------------------

# full run:
MCMC_ITER <- 110L
MCMC_WARMUP <- 100L
MCMC_CHAINS <- 25L
THIN <- 5L
CORES <- 25L
NSIM <- 100L

# testing:
# MCMC_ITER <- 10L
# MCMC_WARMUP <- 9L
# MCMC_CHAINS <- 1L
# THIN <- 1L
# CORES <- 1L
# NSIM <- 1L

RUN_MCMC <- TRUE
INDEX_CORES <- 2L

# end setup -----------------------------------------------------------

# remotes::install_github("https://github.com/pbs-assess/sdmTMB",
#   ref = "mvrfrw")

library(tidyverse)
library(sdmTMB)
library(ggplot2)
library(sdmTMBextra)

ncores <- parallel::detectCores() 
future::plan(future::multisession, workers = 5L)

# make subdirectories for storage
dir.create("data/fits", recursive = TRUE, showWarnings = FALSE)


# downscale data and predictive grid
dat_in <- readRDS(here::here("data", "catch_survey_sbc.rds")) 


# make year key representing pink/sockeye cycle lines
yr_key <- data.frame(
  year = unique(dat_in$year)
) %>% 
  arrange(year) %>% 
  mutate(
    sox_cycle = rep(1:4, length.out = 25L) %>% 
      as.factor(),
    pink_cycle = rep(1:2, length.out = 25L) %>% 
      as.factor()
  )

# downscale data and predictive grid
dat <- dat_in %>% 
  mutate(
    year_f = as.factor(year),
    yday = lubridate::yday(date),
    utm_x_1000 = utm_x / 1000,
    utm_y_1000 = utm_y / 1000,
    effort = log(volume_km3 * 500),
    scale_dist = scale(as.numeric(dist_to_coast_km))[ , 1],
    scale_depth = scale(as.numeric(target_depth))[ , 1],
    day_night = as.factor(day_night)) %>% 
  filter(!species == "steelhead") %>% 
  droplevels() %>% 
  left_join(., yr_key, by = "year")


## mesh shared among species
dat_coords <- dat %>% 
  filter(species == "chinook") %>% 
  select(utm_x_1000, utm_y_1000) %>% 
  as.matrix()
inla_mesh_raw <- INLA::inla.mesh.2d(
  loc = dat_coords,
  max.edge = c(2, 10) * 500,
  cutoff = 30,
  offset = c(10, 50)
)  
spde <- make_mesh(
  dat %>% 
    filter(species == "chinook"),
  c("utm_x_1000", "utm_y_1000"),
  mesh = inla_mesh_raw
) 


dat_tbl <- dat %>%
  group_by(species) %>%
  group_nest()


index_grid_hss <- readRDS(here::here("data", "index_hss_grid.rds")) %>% 
  mutate(day_night = as.factor(day_night),
         trim = ifelse(
           season_f == "wi" & utm_y_1000 < 5551, "yes", "no"
         )) %>%
  #subset to northern domain
  filter(trim == "no") %>% 
  left_join(., yr_key, by = "year")

sp_scalar <- 1 * (13 / 1000) * 500


## FIT MODEL TO EACH SPECIES ---------------------------------------------------

dat_tbl$fit <- furrr::future_map2(
  dat_tbl$data, dat_tbl$species,
  function(dat_in, sp) {
    if (sp == "pink") {
      sdmTMB(
        n_juv ~ 0 + season_f + day_night + survey_f + scale_dist +
          scale_depth + pink_cycle,
        offset = dat_in$effort,
        data = dat_in,
        mesh = spde,
        family = sdmTMB::nbinom2(),
        spatial = "off",
        spatial_varying = ~ 0 + season_f,
        time = "year",
        spatiotemporal = "rw",
        anisotropy = TRUE,
        groups = "season_f",
        control = sdmTMBcontrol(
          map = list(
            ln_tau_Z = factor(
              rep(1, times = length(unique(dat$season_f)))
            )
          )
        ),
        silent = FALSE
      )
    } else if (sp == "sockeye") {
      sdmTMB(
        n_juv ~ 0 + season_f + day_night + survey_f + scale_dist +
          scale_depth + sox_cycle,
        offset = dat_in$effort,
        data = dat_in,
        mesh = spde,
        family = sdmTMB::nbinom2(),
        spatial = "off",
        spatial_varying = ~ 0 + season_f,
        time = "year",
        spatiotemporal = "rw",
        anisotropy = TRUE,
        groups = "season_f",
        control = sdmTMBcontrol(
          map = list(
            ln_tau_Z = factor(
              rep(1, times = length(unique(dat$season_f)))
            )
          )
        ),
        silent = FALSE
      )
    } else {
      sdmTMB(
        n_juv ~ 0 + season_f + day_night + survey_f + scale_dist +
          scale_depth,
        offset = dat_in$effort,
        data = dat_in,
        mesh = spde,
        family = sdmTMB::nbinom2(),
        spatial = "off",
        spatial_varying = ~ 0 + season_f,
        time = "year",
        spatiotemporal = "rw",
        anisotropy = TRUE,
        groups = "season_f",
        control = sdmTMBcontrol(
          map = list(
            ln_tau_Z = factor(
              rep(1, times = length(unique(dat$season_f)))
            )
          )
        ),
        silent = FALSE
      )
    }
  }
)


## UPDATE MCMC DRAWS -----------------------------------------------------------

if (RUN_MCMC) {
  set.seed(456)
  purrr::map2(
    dat_tbl$fit, dat_tbl$species, function (x, y) {
      object <- x
      samp <- sample_mle_mcmc(
        object, mcmc_iter = MCMC_ITER, mcmc_warmup = MCMC_WARMUP, mcmc_chains = MCMC_CHAINS,
        stan_args = list(thin = THIN, cores = CORES)
      )
      obj <- object$tmb_obj
      random <- unique(names(obj$env$par[obj$env$random]))
      pl <- as.list(object$sd_report, "Estimate")
      fixed <- !(names(pl) %in% random)
      map <- lapply(pl[fixed], function(x) factor(rep(NA, length(x))))
      obj <- TMB::MakeADFun(obj$env$data, pl, map = map, DLL = "sdmTMB")
      obj_mle <- object
      obj_mle$tmb_obj <- obj
      obj_mle$tmb_map <- map
      sim_out <- simulate(
        obj_mle, mcmc_samples = sdmTMBextra::extract_mcmc(samp), nsim = NSIM
      )
      saveRDS(
        sim_out,
        here::here("data", "fits",
          paste(y, "_mcmc_draws_nb2_mvrfrw.rds", sep = ""))
      )
    }
  )
}

dat_tbl$sims <- purrr::map(
  dat_tbl$species,
  ~ readRDS(
    here::here("data", "fits", 
               paste(.x, "_mcmc_draws_nb2_mvrfrw.rds", sep = ""))
  )
)


# make a tibble for each species simulations
sim_tbl <- purrr::pmap(
  list(dat_tbl$species, dat_tbl$fit, dat_tbl$sims),
  function (sp, fits, x) {
    tibble(
      species = sp,
      iter = seq(1, ncol(x), by = 1),
      sim_dat = lapply(seq_len(ncol(x)), function(i) {
        # use fits instead of data in tibble because mismatched from extra_time
        fits$data %>% 
          mutate(sim_catch = x[ , i])
      })
    )
  }
) %>% 
  bind_rows() %>% 
  left_join(., 
            dat_tbl %>% select(species, fit), 
            by = c("species"))


## FIT SIMS  -------------------------------------------------------------------

gc()
dir.create(here::here("data", "fits", "sim_fit"), showWarnings = FALSE)
# fit model to species 

sp_vec <- unique(sim_tbl$species)

future::plan(future::multisession, workers = INDEX_CORES)
# if (FALSE) {
for (i in seq_along(sp_vec)) {
  sim_tbl_sub <- sim_tbl %>% filter(species == sp_vec[i])
  furrr::future_pmap(
  # purrr::pmap(
    list(sim_tbl_sub$sim_dat, sim_tbl_sub$fit, sim_tbl_sub$iter), 
    function (x, fit, iter) {
      if (sp_vec[i] %in% c("chinook", "coho", "chum")) {
        sim_fit <- sdmTMB(
          sim_catch ~ 0 + season_f + day_night + survey_f + scale_dist +
            scale_depth,
          offset = x$effort,
          data = x,
          mesh =  fit$spde,
          family = sdmTMB::nbinom2(),
          spatial = "off",
          spatial_varying = ~ 0 + season_f,
          time = "year",
          spatiotemporal = "rw",
          anisotropy = TRUE,
          groups = "season_f",
          control = sdmTMBcontrol(
            map = list(
              ln_tau_Z = factor(
                rep(1, times = length(unique(x$season_f)))
              )
            )
          ),
          silent = FALSE
        )
      } else if (sp_vec[i] == "pink") {
        sim_fit <- sdmTMB(
          sim_catch ~ 0 + season_f + day_night + survey_f + scale_dist +
            scale_depth + pink_cycle,
          offset = x$effort,
          data = x,
          mesh = spde,
          family = sdmTMB::nbinom2(),
          spatial = "off",
          spatial_varying = ~ 0 + season_f,
          time = "year",
          spatiotemporal = "rw",
          anisotropy = TRUE,
          groups = "season_f",
          control = sdmTMBcontrol(
            map = list(
              ln_tau_Z = factor(
                rep(1, times = length(unique(x$season_f)))
              )
            )
          ),
          silent = FALSE
        )
      } else if (sp_vec[i] == "sockeye") {
        sim_fit <- sdmTMB(
          sim_catch ~ 0 + season_f + day_night + survey_f + scale_dist +
            scale_depth + sox_cycle,
          offset = x$effort,
          data = x,
          mesh = spde,
          family = sdmTMB::nbinom2(),
          spatial = "off",
          spatial_varying = ~ 0 + season_f,
          time = "year",
          spatiotemporal = "rw",
          anisotropy = TRUE,
          groups = "season_f",
          control = sdmTMBcontrol(
            map = list(
              ln_tau_Z = factor(
                rep(1, times = length(unique(x$season_f)))
              )
            )
          ),
          silent = FALSE
        )
      }
      
      # recover pars
      fix <- tidy(sim_fit, effects = "fixed") 
      ran <- tidy(sim_fit, effects = "ran_pars") 
      
      # pull upsilon estimate separately (not currently generated by predict)
      est <- as.list(sim_fit$sd_report, "Estimate", report = TRUE)
      se <- as.list(sim_fit$sd_report, "Std. Error", report = TRUE)
      upsilon <- data.frame(
        term = "sigma_U",
        log_est = est$log_sigma_U,
        log_se = se$log_sigma_U
      ) %>% 
        mutate(
          estimate = exp(log_est),
          std.error = exp(log_se) 
        ) %>% 
        select(term, estimate, std.error)
      
      pars <- rbind(fix, ran, upsilon) %>% 
        # add unique identifier for second range term
        group_by(term) %>% 
        mutate(
          iter = iter,
          par_id = row_number(),
          term = ifelse(par_id > 1, paste(term, par_id, sep = "_"), term)
        ) %>% 
        ungroup() 
      
      file_name <- paste(sp_vec[i], "_", iter, "_pars.rds", sep = "")
      saveRDS(pars, here::here("data", "fits", "sim_fit", file_name))
      
      su_preds <- predict(
        sim_fit,
        newdata = index_grid_hss %>%
          filter(season_f == "su"),
        se_fit = FALSE, re_form = NULL, return_tmb_object = TRUE)
      su_index <- get_index(su_preds, area = sp_scalar, bias_correct = TRUE) %>%
        mutate(season_f = "su",
               species = sp_vec[i],
               iter = iter)
      fall_preds <- predict(
        sim_fit, 
        newdata = index_grid_hss %>%
          filter(season_f == "wi"),
        se_fit = FALSE, re_form = NULL, return_tmb_object = TRUE
      )
      fall_index <- get_index(fall_preds, area = sp_scalar, bias_correct = TRUE) %>%
        mutate(season_f = "wi",
               species = sp_vec[i],
               iter = iter)
      
      file_name2 <- paste(sp_vec[i], "_", iter, "_index.rds", sep = "")
      saveRDS(rbind(su_index, fall_index),
              here::here("data", "fits", "sim_fit", file_name2))
    }
  )
}



# }
# # import saved sim fits 
# sim_fit_list <- purrr::map(
#   sim_tbl$species,
#   ~ readRDS(
#     here::here("data", "fits", "sim_fit", paste(.x, "_nb2_mvrfrw.rds", sep = ""))
#   )
# )
# 
# sim_tbl$sim_fit <- do.call(c, sim_fit_list)



## RECOVER PARAMETERS ----------------------------------------------------------

# extract fixed and ran effects pars from simulations
# sim_tbl$pars <- purrr::map(
#   sim_tbl$sim_fit, function (x) {
#     fix <- tidy(x, effects = "fixed") 
#     ran <- tidy(x, effects = "ran_pars") 
#     
#     # pull upsilon estimate separately (not currently generated by predict)
#     est <- as.list(x$sd_report, "Estimate", report = TRUE)
#     se <- as.list(x$sd_report, "Std. Error", report = TRUE)
#     upsilon <- data.frame(
#       term = "sigma_U",
#       log_est = est$log_sigma_U,
#       log_se = se$log_sigma_U
#     ) %>% 
#       mutate(
#         estimate = exp(log_est),
#         std.error = exp(log_se) 
#       ) %>% 
#       select(term, estimate, std.error)
#     
#     rbind(fix, ran, upsilon) %>% 
#       # add unique identifier for second range term
#       group_by(term) %>% 
#       mutate(
#         par_id = row_number(),
#         term = ifelse(par_id > 1, paste(term, par_id, sep = "_"), term)
#       ) %>% 
#       ungroup() 
#   }
# )
# 
# sim_pars <- sim_tbl %>% 
#   select(species, iter, pars) %>% 
#   unnest(cols = c(pars)) %>% 
#   mutate(
#     iter = as.factor(iter),
#     species = abbreviate(species, minlength = 3),
#     term = fct_recode(
#       as.factor(term), 
#       "diel" = "day_nightNIGHT", "depth" = "scale_depth",
#       "dist" = "scale_dist",
#       "spring_int" = "season_fsp", 
#       "summer_int" = "season_fsu", "fall_int" = "season_fwi", 
#       "survey_design" = "survey_fipes"
#     )
#   ) 
# dir.create(here::here("data", "preds"), showWarnings = FALSE)
# saveRDS(sim_pars, here::here("data", "preds", "sim_pars_mvrfrw.rds"))


# as above but for fitted models
# fit_effs <- purrr::map2(
#   sim_tbl$fit, sim_tbl$species, function (x, sp) {
#     fix <- tidy(x, effects = "fixed")
#     ran <- tidy(x, effects = "ran_pars")
#     
#     # pull upsilon estimate separately (not currently generated by predict)
#     est <- as.list(x$sd_report, "Estimate", report = TRUE)
#     se <- as.list(x$sd_report, "Std. Error", report = TRUE)
#     upsilon <- data.frame(
#       term = "sigma_U",
#       log_est = est$log_sigma_U,
#       log_se = se$log_sigma_U
#     ) %>% 
#       mutate(
#         estimate = exp(log_est),
#         std.error = exp(log_se) 
#       ) %>% 
#       select(term, estimate, std.error)
#     
#     rbind(fix, ran, upsilon) %>% 
#       mutate(species = abbreviate(sp, minlength = 3)) %>% 
#       # add unique identifier for second range term
#       group_by(term) %>% 
#       mutate(
#         par_id = row_number(),
#         term = ifelse(par_id > 1, paste(term, par_id, sep = "_"), term)
#       ) %>% 
#       ungroup()
#   }
# ) %>% 
#   bind_rows() %>% 
#   mutate(
#     term = fct_recode(
#       as.factor(term), "diel" = "day_nightNIGHT", "depth" = "scale_depth",
#       "dist" = "scale_dist",
#       "spring_int" = "season_fsp", 
#       "summer_int" = "season_fsu", "fall_int" = "season_fwi", 
#       "survey_design" = "survey_fipes"
#     )
#   )
# 
# sim_box <- ggplot() +
#   geom_boxplot(data = sim_pars,
#                aes(x = species, y = estimate)) +
#   geom_point(data = fit_effs,
#              aes(x = species, y = estimate), colour = "red") +
#   facet_wrap(~term, scales = "free", ncol = 3) +
#   labs(y = "Parameter Estimate", x =  "Species") +
#   ggsidekick::theme_sleek() 
# 
# dir.create(here::here("figs"), showWarnings = FALSE)
# dir.create(here::here("figs", "ms_figs_season_mvrw"), showWarnings = FALSE)
# png(here::here("figs", "ms_figs_season_mvrw", "par_recovery_sim_box_mcmc.png"), 
#     height = 8, width = 8, units = "in", res = 200)
# sim_box
# dev.off()



# RECOVER INDEX ----------------------------------------------------------------

# index grid with cycle lines added



# future::plan(future::multisession, workers = 2L)
# # estimate season-specific index for each simulation draw 
# for (i in seq_along(sp_vec)) {
#   sim_tbl_sub <- sim_tbl %>% filter(species == sp_vec[i])
#   sim_ind_list_summer <- furrr::future_map(
#     sim_tbl_sub$sim_fit[1:100],
#     function (x) {
#       pp <- predict(x,
#                     newdata = index_grid_hss %>%
#                       filter(season_f == "su"),
#                     se_fit = FALSE, re_form = NULL, return_tmb_object = TRUE)
#       get_index(pp, area = sp_scalar, bias_correct = TRUE) %>%
#         mutate(season_f = "su",
#                species = sp_vec[i])
#     }
#   )
#   saveRDS(
#     sim_ind_list_summer ,
#     here::here("data", "fits", "sim_fit",
#                paste(sp_vec[i], "_summer_sim_index_final_mvrfrw.rds", sep = ""))
#   )
#   sim_ind_list_fall <- furrr::future_map(
#     sim_tbl_sub$sim_fit[1:100],
#     function (x) {
#       pp <- predict(x, 
#                     newdata = index_grid_hss %>%
#                       filter(season_f == "wi"),
#                     se_fit = FALSE, re_form = NULL, return_tmb_object = TRUE)
#       get_index(pp, area = sp_scalar, bias_correct = TRUE) %>%
#         mutate(season_f = "wi",
#                species = sp_vec[i])
#     }
#   )
#   saveRDS(
#     sim_ind_list_fall ,
#     here::here("data", "fits", "sim_fit",
#                paste(sp_vec[i], "_fall_sim_index_final_mvrfrw.rds", sep = ""))
#   )
# }


# import saved indices from all_species_fit_season.R
# true_index_list <- readRDS(
#   here::here("data", "fits", "season_index_list_mvrfrw.rds")
# )

# true_index_summer <- furrr::future_map2(
#   dat_tbl$fit, dat_tbl$species,
#   function (x, y) {
#     pp <- predict(x, 
#                   newdata = index_grid_hss %>%
#                     filter(season_f == "su"),
#                   se_fit = FALSE, re_form = NULL, return_tmb_object = TRUE)
#     get_index(pp, area = sp_scalar, bias_correct = TRUE) %>%
#       mutate(season_f = "su",
#              species = y)
#   }
# )
# true_index_fall <- furrr::future_map2(
#   dat_tbl$fit, dat_tbl$species,
#   function (x, y) {
#     pp <- predict(x, 
#                   newdata = index_grid_hss %>%
#                     filter(season_f == "wi"),
#                   se_fit = FALSE, re_form = NULL, return_tmb_object = TRUE)
#     get_index(pp, area = sp_scalar, bias_correct = TRUE) %>%
#       mutate(season_f = "wi",
#              species = y)
#   }
# ) 

# true_ind_dat <- #true_index_list %>%
#   #bind_rows() %>% 
#   rbind(true_index_summer %>% bind_rows(), 
#         true_index_fall %>% bind_rows()) %>% 
#   mutate(
#     season = fct_recode(season_f, "summer" = "su", "fall" = "wi"),
#     survey = case_when(
#       season == "fall" & year %in% fall_years ~ "sampled",
#       season == "summer" & year %in% summer_years ~ "sampled",
#       TRUE ~ "no survey"
#     ),
#     log_lwr = log_est - (1.96 * se),
#     log_upr = log_est + (1.96 * se),
#     year_f = as.factor(year)
#   )
# 
# 
# sim_index_list_summer <- purrr::map(
#   sp_vec,
#   ~ readRDS(
#     here::here("data", "fits", "sim_fit",
#                paste(.x, "_summer_sim_index_final_mvrfrw.rds", sep = ""))
#   )
# )
# sim_index_list_fall <- purrr::map(
#   sp_vec,
#   ~ readRDS(
#     here::here("data", "fits", "sim_fit",
#                paste(.x, "_fall_sim_index_final_mvrfrw.rds", sep = ""))
#   ) 
# )

# n_iter <- length(sim_index_list_fall[[1]]) #how many sims per species?
# 
# sim_ind_dat <- tibble(
#   # species = c(rep(sp_vec, each = n_iter), rep(sp_vec, each = n_iter)),
#   iter = rep(seq(1, n_iter, by = 1), times = (length(sp_vec) * 2)),
#   sim_index = c(do.call(c, sim_index_list_summer), 
#                 do.call(c, sim_index_list_fall))
# ) %>%
#   unnest(cols = "sim_index") %>%
#   left_join(
#     ., 
#     true_ind_dat %>% 
#       select(species, year, year_f, season_f, true_log_est = log_est),
#     by = c("species", "year", "season_f")) %>% 
#   mutate(
#     season = fct_recode(season_f, "summer" = "su", "fall" = "wi"),
#     resid_est = true_log_est - log_est
#   )

# 
# png(here::here("figs", "ms_figs_season", "sim_index.png"), 
#     height = 8, width = 8, units = "in", res = 200)
# ggplot() +
#   geom_boxplot(data = sim_ind_dat,
#                aes(x = year_f, y = log_est)) +
#   geom_point(data = true_ind_dat %>% filter(species %in% sp_vec),
#              aes(x = year_f, y = log_est, colour = survey)) +
#   facet_grid(species~season, scales = "free_y") +
#   ggsidekick::theme_sleek() +
#   theme(legend.position = "top") +
#   scale_x_discrete(breaks = seq(2000, 2020, by = 5)) +
#   labs(y = "Log Estimated Abundance") +
#   theme(axis.title.x = element_blank())
# dev.off()
# 
# png(here::here("figs", "ms_figs_season", "resid_index.png"), 
#     height = 8, width = 8, units = "in", res = 200)
# ggplot() +
#   geom_boxplot(data = sim_ind_dat,
#                aes(x = year_f, y = resid_est)) +
#   geom_hline(yintercept = 0, lty = 2, colour = "red") +
#   facet_grid(species~season, scales = "free_y") +
#   ggsidekick::theme_sleek() +
#   theme(legend.position = "top") +
#   scale_x_discrete(breaks = seq(2000, 2020, by = 5)) +
#   labs(y = "Index Residuals") +
#   theme(axis.title.x = element_blank())
# dev.off()

