### Can fit parameters be recovered?
## Use simulated data generated by model in chinook_fit to determine whether key
## parameters can be reliably recovered.
## Sep 29, 2022
## Reran Oct 26: parameters recovered well for most species except range biased 
# high and headrope depth coefficients uncertain for chum in particular;
# consider rerunning with smooth for headrope, not cat. effects
## Reran Jan 31: "final" model after comparing spatiotemporal structures with
# cross validation
## Reran April 21: 


library(tidyverse)
library(sdmTMB)
library(ggplot2)
library(sdmTMBextra)

ncores <- parallel::detectCores() 
future::plan(future::multisession, workers = ncores - 3)


# make subdirectories for storage
dir.create("data/fits", recursive = TRUE, showWarnings = FALSE)


# fitted model from all_species_fit.R
all_fit_tbl <- readRDS(
  here::here("data", "fits", "all_spatial_varying_nb2_final.rds")
  )


#simulate from Stan output fixing FEs at MLE
# set.seed(456)
# sims_list <- furrr::future_map(
#   all_fit_tbl$fit, function (x) {
#     object <- x
#     samp <- sample_mle_mcmc(object, mcmc_iter = 120, mcmc_warmup = 100)
# 
#     obj <- object$tmb_obj
#     random <- unique(names(obj$env$par[obj$env$random]))
#     pl <- as.list(object$sd_report, "Estimate")
#     fixed <- !(names(pl) %in% random)
#     map <- lapply(pl[fixed], function(x) factor(rep(NA, length(x))))
#     obj <- TMB::MakeADFun(obj$env$data, pl, map = map, DLL = "sdmTMB")
#     obj_mle <- object
#     obj_mle$tmb_obj <- obj
#     obj_mle$tmb_map <- map
#     simulate(obj_mle, mcmc_samples = sdmTMBextra::extract_mcmc(samp), nsim = 20)
#   }
# )
# saveRDS(sims_list,
#         here::here("data", "fits", "nb_mcmc_draws_nb2_final.rds"))

sims_list <- readRDS(here::here("data", "fits", "nb_mcmc_draws_nb2_final.rds"))

all_fit_tbl$sims <- sims_list 

# check residuals
dharma_list <- purrr::map2(all_fit_tbl$sims, all_fit_tbl$fit,
                           function (x, y) {
  pred_fixed <- y$family$linkinv(
    predict(y,
            newdata = y$data)$est_non_rf
  )
  r_nb <- DHARMa::createDHARMa(
    simulatedResponse = x,
    observedResponse = y$data$n_juv,
    fittedPredictedResponse = pred_fixed
  )
  DHARMa::testResiduals(r_nb)
}
)

## for each simulated dataset, refit model, recover pars and store

# make a tibble for each species simulations
sim_tbl <- purrr::pmap(
  list(all_fit_tbl$species, all_fit_tbl$fit, all_fit_tbl$sims),
  function (sp, fits, x) {
    tibble(
      species = sp,
      iter = seq(1, ncol(x), by = 1),
      sim_dat = lapply(seq_len(ncol(x)), function(i) {
        # use fits instead of data in tibble because mismatched from extra_time
        fits$data %>% 
          mutate(sim_catch = x[ , i])
      })
    )
  }
) %>% 
  bind_rows() %>% 
  left_join(., 
            all_fit_tbl %>% select(species, fit), 
            by = c("species"))

sp_vec <- unique(sim_tbl$species)


## DISPERSION ------------------------------------------------------------------

all_fit_tbl$true_sd <- purrr::map(
  all_fit_tbl$data, ~ sd(.x$n_juv)
)

sim_tbl$sim_sd <- purrr::map(
  sim_tbl$sim_dat, ~ sd(.x$sim_catch)
)

sim_tbl %>% 
  select(species, sim_sd) %>% 
  left_join(., all_fit_tbl %>% select(species, true_sd), by = "species") %>% 
  unnest(cols = c(sim_sd, true_sd)) %>% 
  ggplot(.) +
  geom_boxplot(aes(x = as.factor(species), y = sim_sd)) +
  geom_point(aes(x = as.factor(species), y = true_sd), colour = "red")
  

## PROPORTION OF ZEROS ---------------------------------------------------------

# proportion zeros
purrr::map2(all_fit_tbl$data, all_fit_tbl$sims, function(x, y) {
  (sum(x$n_juv == 0) / length(x$n_juv)) / (sum(y == 0) / length(y))
})


## FIT SIMS  -------------------------------------------------------------------

# fit model to species 
for (i in seq_along(sp_vec)) {
  sim_tbl_sub <- sim_tbl %>% filter(species == sp_vec[i])
  fit <- purrr::map2(
    sim_tbl_sub$sim_dat, sim_tbl_sub$fit, 
    function (x, fit) {
      if (sp_vec[i] %in% c("pink")) {
        sdmTMB(
          sim_catch ~ 0 + season_f + day_night + survey_f + 
            scale_depth + scale_dist
          ,
          offset = x$effort,
          data = x,
          mesh =  fit$spde,
          family = sdmTMB::nbinom2(),
          spatial = "off",
          spatiotemporal = "off",
          spatial_varying = ~ 0 + season_f + year_f,
          time_varying = ~ 1,
          time_varying_type = "rw0",
          time = "ys_index",
          extra_time = fit$extra_time,
          anisotropy = FALSE,
          control = sdmTMBcontrol(
            newton_loops = 1,
            map = list(
              # 1 per season, fix all years to same value
              ln_tau_Z = factor(
                c(1, 2, 3, rep(4, times = length(unique(x$year)) - 1))
              )
            )
          ),
          silent = FALSE
        )
      } else {
        sdmTMB(
          sim_catch ~ 0 + season_f + day_night + survey_f + 
            scale_depth + scale_dist
          ,
          offset = x$effort,
          data = x,
          mesh =  fit$spde,
          family = sdmTMB::nbinom2(),
          spatial = "off",
          spatiotemporal = "off",
          spatial_varying = ~ 0 + season_f + year_f,
          time_varying = ~ 1,
          time_varying_type = "rw0",
          time = "ys_index",
          extra_time = fit$extra_time,
          anisotropy = TRUE,
          control = sdmTMBcontrol(
            newton_loops = 1,
            map = list(
              # 1 per season, fix all years to same value
              ln_tau_Z = factor(
                c(1, 2, 3, rep(4, times = length(unique(x$year)) - 1))
              )
            )
          ),
          silent = FALSE
        )
      }
    }
  )
  saveRDS(
    fit,
    here::here("data", "fits", "sim_fit", 
               paste(sp_vec[i], "_nb2_final.rds", sep = ""))
  )
  }


# import saved sim fits 
sim_fit_list <- purrr::map(
  sp_vec,
  ~ readRDS(
    here::here("data", "fits", "sim_fit", paste(.x, "_nb2_final.rds", sep = ""))
  )
)

sim_tbl$sim_fit <- do.call(c, sim_fit_list)



## RECOVER PARAMETERS ----------------------------------------------------------

# extract fixed and ran effects pars from simulations
sim_tbl$pars <- purrr::map(
  sim_tbl$sim_fit, function (x) {
    fix <- tidy(x, effects = "fixed")
    ran <- tidy(x, effects = "ran_pars")
    rbind(fix, ran) %>% 
      # add unique identifier for second range term
      group_by(term) %>% 
      mutate(
        par_id = row_number(),
        term = ifelse(par_id > 1, paste(term, par_id, sep = "_"), term)
      ) %>% 
      ungroup() 
  }
)

sim_pars <- sim_tbl %>% 
  select(species, iter, pars) %>% 
  unnest(cols = c(pars)) %>% 
  mutate(
    iter = as.factor(iter),
    species = abbreviate(species, minlength = 3),
    term = fct_recode(
      as.factor(term), 
      "diel" = "day_nightNIGHT", "depth" = "scale_depth",
      "dist" = "scale_dist",
      "spring_int" = "season_fsp", 
      "summer_int" = "season_fsu", "fall_int" = "season_fwi", 
      "spring_omega" = "sigma_Z", "summer_omega" = "sigma_Z_2",
      "fall_omega" = "sigma_Z_3", "year_omega" = "sigma_Z_4", 
      "survey_design" = "survey_fipes"
    )
  ) 
saveRDS(sim_pars, here::here("data", "preds", "sim_pars.rds"))


# as above but for fitted models
fit_effs <- purrr::map2(
  sim_tbl$fit, sim_tbl$species, function (x, sp) {
    fix <- tidy(x, effects = "fixed")
    ran <- tidy(x, effects = "ran_pars")
    rbind(fix, ran) %>% 
      mutate(species = abbreviate(sp, minlength = 3)) %>% 
      # add unique identifier for second range term
      group_by(term) %>% 
      mutate(
        par_id = row_number(),
        term = ifelse(par_id > 1, paste(term, par_id, sep = "_"), term)
      ) %>% 
      ungroup()
  }
) %>% 
  bind_rows() %>% 
  mutate(
    term = fct_recode(
      as.factor(term), "diel" = "day_nightNIGHT", "depth" = "scale_depth",
      "dist" = "scale_dist",
      "spring_int" = "season_fsp", 
      "summer_int" = "season_fsu", "fall_int" = "season_fwi", 
      "spring_omega" = "sigma_Z", "summer_omega" = "sigma_Z_2",
      "fall_omega" = "sigma_Z_3", "year_omega" = "sigma_Z_4", 
      "survey_design" = "survey_fipes"
    )
  )

sim_box <- ggplot() +
  geom_boxplot(data = sim_pars, aes(x = species, y = estimate)) +
  geom_point(data = fit_effs, aes(x = species, y = estimate), colour = "red") +
  facet_wrap(~term, scales = "free", ncol = 3) +
  labs(y = "Parameter Estimate", x =  "Species") +
  ggsidekick::theme_sleek() 

png(here::here("figs", "ms_figs_season", "par_recovery_sim_box_mcmc.png"), 
    height = 8, width = 8, units = "in", res = 200)
sim_box
dev.off()



# RECOVER INDEX ----------------------------------------------------------------

cov_in <- sim_tbl$fit[[1]]$data 
# define years where survey occurred
summer_years <- sim_tbl$fit[[1]]$data %>% 
  filter(season_f == "su", 
         # remove 2021 since only partial survey
         !year_f == "2021") %>%
  pull(year) %>% 
  unique()
fall_years <- sim_tbl$fit[[1]]$data %>% 
  filter(season_f == "wi",
         # remove 2020 since most of survey was outside of grid
         !year_f == "2020") %>%
  pull(year) %>% 
  unique()
year_season_key <- readRDS(here::here("data", "year_season_key.rds"))


index_grid_hss <- readRDS(here::here("data", "index_hss_grid.rds")) %>% 
  mutate(
    scale_dist = (dist_to_coast_km - mean(cov_in$dist_to_coast_km)) /
      sd(cov_in$dist_to_coast_km),
    scale_depth = (target_depth - mean(cov_in$target_depth)) /
      sd(cov_in$target_depth)
    )

sp_scalar <- 1 * (13 / 1000)


# estimate index for each simulation draw
for (i in seq_along(sp_vec)) {
  sim_tbl_sub <- sim_tbl %>% filter(species == sp_vec[i])
  sim_ind_list <- purrr::map(
    sim_tbl_sub$sim_fit,
    function (x) {
      pp <- predict(x, newdata = index_grid_hss,
                    se_fit = FALSE, re_form = NULL, return_tmb_object = TRUE)
      get_index(pp, area = sp_scalar, bias_correct = TRUE) %>% 
        left_join(., year_season_key, by = "ys_index")
    }
  )  
  saveRDS(
    sim_ind_list,
    here::here("data", "fits", "sim_fit",
               paste(sp_vec[i], "_sim_index_final.rds", sep = ""))
  )
}


# import saved indices from all_species_fit_season.R
true_index_list <- readRDS(
  here::here("data", "fits", "season_index_list.rds")
)

true_ind_dat <- tibble(
  species = sp_vec,
  true_index = true_index_list
) %>% 
  unnest(cols = "true_index") %>% 
  left_join(., year_season_key, by = "ys_index") %>% 
  filter(!season_f == "sp") %>% 
  mutate(
    season = fct_recode(season_f, "summer" = "su", "fall" = "wi"),
    survey = case_when(
      season == "fall" & year %in% fall_years ~ "sampled",
      season == "summer" & year %in% summer_years ~ "sampled",
      TRUE ~ "no survey"
    ),
    log_lwr = log_est - (1.96 * se),
    log_upr = log_est + (1.96 * se),
    year = as.factor(year)
  )


sim_index_list <- purrr::map(
  sp_vec,
  ~ readRDS(
    here::here("data", "fits", "sim_fit",
               paste(.x, "_sim_index_final.rds", sep = ""))
  )
)

sim_tbl$sim_index <- do.call(c, sim_index_list)

sim_ind_dat <- sim_tbl %>%
  select(species, iter, sim_index) %>% 
  unnest(cols = "sim_index") %>% 
  filter(!season_f == "sp") %>% 
  left_join(
    ., 
    true_ind_dat %>% select(species, ys_index, true_log_est = log_est),
    by = c("species", "ys_index")) %>% 
  mutate(
    season = fct_recode(season_f, "summer" = "su", "fall" = "wi"),
    year = as.factor(year),
    resid_est = true_log_est - log_est
  )


png(here::here("figs", "ms_figs_season", "sim_index.png"), 
    height = 8, width = 8, units = "in", res = 200)
ggplot() +
  geom_boxplot(data = sim_ind_dat,
               aes(x = year, y = log_est)) +
  geom_point(data = true_ind_dat,
             aes(x = year, y = log_est, colour = survey)) +
  facet_grid(species~season, scales = "free_y") +
  ggsidekick::theme_sleek() +
  theme(legend.position = "top") +
  scale_x_discrete(breaks = seq(2000, 2020, by = 5)) +
  labs(y = "Log Estimated Abundance") +
  theme(axis.title.x = element_blank())
dev.off()

png(here::here("figs", "ms_figs_season", "resid_index.png"), 
    height = 8, width = 8, units = "in", res = 200)
ggplot() +
  geom_boxplot(data = sim_ind_dat,
               aes(x = year, y = resid_est)) +
  geom_hline(yintercept = 0, lty = 2, colour = "red") +
  facet_grid(species~season, scales = "free_y") +
  ggsidekick::theme_sleek() +
  theme(legend.position = "top") +
  scale_x_discrete(breaks = seq(2000, 2020, by = 5)) +
  labs(y = "Index Residuals") +
  theme(axis.title.x = element_blank())
dev.off()