### Can fit parameters be recovered?
## Use simulated data generated by model in all_species_fit_season_mvrw to 
## determine whether parameters can be recovered.
## Sep 27, 2023


library(tidyverse)
library(sdmTMB)
library(ggplot2)
library(sdmTMBextra)

ncores <- parallel::detectCores() 
future::plan(future::multisession, workers = 5L)

# make subdirectories for storage
dir.create("data/fits", recursive = TRUE, showWarnings = FALSE)

# fitted model from all_species_fit.R
all_fit_tbl1 <- readRDS(
  here::here("data", "fits", "all_spatial_varying_nb2_mvrfrw_final.rds")
)


## UPDATE FITS -----------------------------------------------------------------

# replace pink/sockeye fits
sox_dat1 <- all_fit_tbl1 %>% 
  filter(species == "sockeye") %>% 
  select(data) %>% 
  unnest(cols = c(data))

# add species-specific cycles 
yr_key <- data.frame(
  year = unique(sox_dat1$year)
) %>% 
  arrange(year) %>% 
  mutate(
    sox_cycle = rep(1:4, length.out = 25L) %>% 
      as.factor(),
    pink_cycle = rep(1:2, length.out = 25L) %>% 
      as.factor()
  )

sox_dat <- sox_dat1 %>% 
  left_join(., yr_key, by = "year")
pink_dat <- all_fit_tbl1 %>% 
  filter(species == "pink") %>% 
  select(data) %>% 
  unnest(cols = c(data)) %>% 
  left_join(., yr_key, by = "year")

sox_fit_cycle <- sdmTMB(
  n_juv ~ 0 + season_f + day_night + survey_f + scale_dist +
    scale_depth + sox_cycle,
  offset = sox_dat$effort,
  data = sox_dat,
  mesh = spde,
  family = sdmTMB::nbinom2(),
  spatial = "off",
  spatial_varying = ~ 0 + season_f,
  time = "year",
  spatiotemporal = "rw",
  anisotropy = TRUE,
  groups = "season_f",
  control = sdmTMBcontrol(
    map = list(
      ln_tau_Z = factor(
        rep(1, times = length(unique(sox_dat$season_f)))
      )
    )
  ),
  silent = FALSE
)

pink_fit_cycle <- sdmTMB(
  n_juv ~ 0 + season_f + day_night + survey_f + scale_dist +
    scale_depth + pink_cycle,
  offset = pink_dat$effort,
  data = pink_dat,
  mesh = spde,
  family = sdmTMB::nbinom2(),
  spatial = "off",
  spatial_varying = ~ 0 + season_f,
  time = "year",
  spatiotemporal = "rw",
  anisotropy = TRUE,
  groups = "season_f",
  control = sdmTMBcontrol(
    map = list(
      ln_tau_Z = factor(
        rep(1, times = length(unique(pink_dat$season_f)))
      )
    )
  ),
  silent = FALSE
)

# combine
trim_tbl <- all_fit_tbl1 %>% 
  filter(species %in% c("pink", "sockeye")) %>% 
  mutate(
    fit = list(pink_fit_cycle, sox_fit_cycle),
    model = rep("mvrfrw_cyc", 2)
  )

all_fit_tbl <- rbind(
  all_fit_tbl1 %>% 
    filter(!species %in% c("pink", "sockeye")),
  trim_tbl
) %>% 
  #drop spare cols since AIC and FEs are wrogn for pink/sockeye
  select(
    species, data, fit, model
  )


## UPDATE MCMC DRAWS -----------------------------------------------------------

# import original mcmc fits, split and save as species-specific files
sims_list_old <- readRDS(
  here::here("data", "fits", "nb_mcmc_draws_nb2_mvrfrw.rds")
)
purrr::map2(
  sims_list_old, all_fit_tbl$species,
  ~ saveRDS(
    .x,
    here::here("data", "fits", 
               paste(.y, "_mcmc_draws_nb2_mvrfrw.rds", sep = ""))
  )
)

# overwrite MCMC sims for pink/sockeye
set.seed(456)
purrr::map2(
  all_fit_tbl$fit, all_fit_tbl$species, function (x, y) {
    if (y %in% c("pink", "sockeye")) {
      object <- x
      samp <- sample_mle_mcmc(
        object, mcmc_iter = 110L, mcmc_warmup = 100L, mcmc_chains = 50L,
        stan_args = list(thin = 5L, cores = 50L)
      )
      obj <- object$tmb_obj
      random <- unique(names(obj$env$par[obj$env$random]))
      pl <- as.list(object$sd_report, "Estimate")
      fixed <- !(names(pl) %in% random)
      map <- lapply(pl[fixed], function(x) factor(rep(NA, length(x))))
      obj <- TMB::MakeADFun(obj$env$data, pl, map = map, DLL = "sdmTMB")
      obj_mle <- object
      obj_mle$tmb_obj <- obj
      obj_mle$tmb_map <- map
      simulate(obj_mle, mcmc_samples = sdmTMBextra::extract_mcmc(samp),
               nsim = 100L)
      saveRDS(
        sims_list,
        here::here("data", "fits", 
                   paste(y, "_mcmc_draws_nb2_mvrfrw.rds", sep = ""))
      )  
    }
  }
)

sims_list <- purrr::map(
  all_fit_tbl$species,
  ~ readRDS(
    here::here("data", "fits", 
               paste(.x, "_mcmc_draws_nb2_mvrfrw.rds", sep = ""))
  )
)

all_fit_tbl$sims <- sims_list

# make a tibble for each species simulations
sim_tbl <- purrr::pmap(
  list(all_fit_tbl$species, all_fit_tbl$fit, all_fit_tbl$sims),
  function (sp, fits, x) {
    tibble(
      species = sp,
      iter = seq(1, ncol(x), by = 1),
      sim_dat = lapply(seq_len(ncol(x)), function(i) {
        # use fits instead of data in tibble because mismatched from extra_time
        fits$data %>% 
          mutate(sim_catch = x[ , i])
      })
    )
  }
) %>% 
  bind_rows() %>% 
  left_join(., 
            all_fit_tbl %>% select(species, fit), 
            by = c("species"))


## FIT SIMS  -------------------------------------------------------------------

gc()
dir.create(here::here("data", "fits", "sim_fit"), showWarnings = FALSE)
# fit model to species 

sp_vec <- c("pink", "sockeye")

future::plan(future::multisession, workers = 2L)
# if (FALSE) {
for (i in seq_along(sp_vec)) {
  sim_tbl_sub <- sim_tbl %>% filter(species == sp_vec[i])
  fit <- furrr::future_map2(
    sim_tbl_sub$sim_dat, sim_tbl_sub$fit, 
    function (x, fit) {
      if (sp_vec[i] %in% c("chinook", "coho", "chum")) {
        sdmTMB(
          sim_catch ~ 0 + season_f + day_night + survey_f + scale_dist +
            scale_depth,
          offset = x$effort,
          data = x,
          mesh =  fit$spde,
          family = sdmTMB::nbinom2(),
          spatial = "off",
          spatial_varying = ~ 0 + season_f,
          time = "year",
          spatiotemporal = "rw",
          anisotropy = TRUE,
          groups = "season_f",
          control = sdmTMBcontrol(
            map = list(
              ln_tau_Z = factor(
                rep(1, times = length(unique(x$season_f)))
              )
            )
          ),
          silent = FALSE
        )
      } else if (sp_vec[i] == "pink") {
        sdmTMB(
          sim_catch ~ 0 + season_f + day_night + survey_f + scale_dist +
            scale_depth + pink_cycle,
          offset = x$effort,
          data = x,
          mesh = spde,
          family = sdmTMB::nbinom2(),
          spatial = "off",
          spatial_varying = ~ 0 + season_f,
          time = "year",
          spatiotemporal = "rw",
          anisotropy = TRUE,
          groups = "season_f",
          control = sdmTMBcontrol(
            map = list(
              ln_tau_Z = factor(
                rep(1, times = length(unique(x$season_f)))
              )
            )
          ),
          silent = FALSE
        )
      }
    } else if (sp_vec[i] == "sockeye") {
      sdmTMB(
        sim_catch ~ 0 + season_f + day_night + survey_f + scale_dist +
          scale_depth + sox_cycle,
        offset = x$effort,
        data = x,
        mesh = spde,
        family = sdmTMB::nbinom2(),
        spatial = "off",
        spatial_varying = ~ 0 + season_f,
        time = "year",
        spatiotemporal = "rw",
        anisotropy = TRUE,
        groups = "season_f",
        control = sdmTMBcontrol(
          map = list(
            ln_tau_Z = factor(
              rep(1, times = length(unique(x$season_f)))
            )
          )
        ),
        silent = FALSE
      )
    }
  )
  saveRDS(
    fit,
    here::here("data", "fits", "sim_fit", 
               paste(sp_vec[i], "_nb2_mvrfrw.rds", sep = ""))
  )
}

# }
# import saved sim fits 
sim_fit_list <- purrr::map(
  sim_tbl$species,
  ~ readRDS(
    here::here("data", "fits", "sim_fit", paste(.x, "_nb2_mvrfrw.rds", sep = ""))
  )
)

sim_tbl$sim_fit <- do.call(c, sim_fit_list)



## RECOVER PARAMETERS ----------------------------------------------------------

# extract fixed and ran effects pars from simulations
sim_tbl$pars <- purrr::map(
  sim_tbl$sim_fit, function (x) {
    fix <- tidy(x, effects = "fixed") 
    ran <- tidy(x, effects = "ran_pars") 
    
    # pull upsilon estimate separately (not currently generated by predict)
    est <- as.list(x$sd_report, "Estimate", report = TRUE)
    se <- as.list(x$sd_report, "Std. Error", report = TRUE)
    upsilon <- data.frame(
      term = "sigma_U",
      log_est = est$log_sigma_U,
      log_se = se$log_sigma_U
    ) %>% 
      mutate(
        estimate = exp(log_est),
        std.error = exp(log_se) 
      ) %>% 
      select(term, estimate, std.error)
    
    rbind(fix, ran, upsilon) %>% 
      # add unique identifier for second range term
      group_by(term) %>% 
      mutate(
        par_id = row_number(),
        term = ifelse(par_id > 1, paste(term, par_id, sep = "_"), term)
      ) %>% 
      ungroup() 
  }
)

sim_pars <- sim_tbl %>% 
  select(species, iter, pars) %>% 
  unnest(cols = c(pars)) %>% 
  mutate(
    iter = as.factor(iter),
    species = abbreviate(species, minlength = 3),
    term = fct_recode(
      as.factor(term), 
      "diel" = "day_nightNIGHT", "depth" = "scale_depth",
      "dist" = "scale_dist",
      "spring_int" = "season_fsp", 
      "summer_int" = "season_fsu", "fall_int" = "season_fwi", 
      "survey_design" = "survey_fipes"
    )
  ) 
dir.create(here::here("data", "preds"), showWarnings = FALSE)
saveRDS(sim_pars, here::here("data", "preds", "sim_pars_mvrfrw.rds"))


# as above but for fitted models
fit_effs <- purrr::map2(
  sim_tbl$fit, sim_tbl$species, function (x, sp) {
    fix <- tidy(x, effects = "fixed")
    ran <- tidy(x, effects = "ran_pars")
    
    # pull upsilon estimate separately (not currently generated by predict)
    est <- as.list(x$sd_report, "Estimate", report = TRUE)
    se <- as.list(x$sd_report, "Std. Error", report = TRUE)
    upsilon <- data.frame(
      term = "sigma_U",
      log_est = est$log_sigma_U,
      log_se = se$log_sigma_U
    ) %>% 
      mutate(
        estimate = exp(log_est),
        std.error = exp(log_se) 
      ) %>% 
      select(term, estimate, std.error)
    
    rbind(fix, ran, upsilon) %>% 
      mutate(species = abbreviate(sp, minlength = 3)) %>% 
      # add unique identifier for second range term
      group_by(term) %>% 
      mutate(
        par_id = row_number(),
        term = ifelse(par_id > 1, paste(term, par_id, sep = "_"), term)
      ) %>% 
      ungroup()
  }
) %>% 
  bind_rows() %>% 
  mutate(
    term = fct_recode(
      as.factor(term), "diel" = "day_nightNIGHT", "depth" = "scale_depth",
      "dist" = "scale_dist",
      "spring_int" = "season_fsp", 
      "summer_int" = "season_fsu", "fall_int" = "season_fwi", 
      "survey_design" = "survey_fipes"
    )
  )

sim_box <- ggplot() +
  geom_boxplot(data = sim_pars,
               aes(x = species, y = estimate)) +
  geom_point(data = fit_effs,
             aes(x = species, y = estimate), colour = "red") +
  facet_wrap(~term, scales = "free", ncol = 3) +
  labs(y = "Parameter Estimate", x =  "Species") +
  ggsidekick::theme_sleek() 

dir.create(here::here("figs"), showWarnings = FALSE)
dir.create(here::here("figs", "ms_figs_season_mvrw"), showWarnings = FALSE)
png(here::here("figs", "ms_figs_season_mvrw", "par_recovery_sim_box_mcmc.png"), 
    height = 8, width = 8, units = "in", res = 200)
sim_box
dev.off()



# RECOVER INDEX ----------------------------------------------------------------

# index grid with cycle lines added
index_grid_hss <- readRDS(here::here("data", "index_hss_grid.rds")) %>% 
  mutate(day_night = as.factor(day_night),
         trim = ifelse(
           season_f == "wi" & utm_y_1000 < 5551, "yes", "no"
         )) %>%
  #subset to northern domain
  filter(trim == "no") %>% 
  left_join(., yr_key, by = "year")

sp_scalar <- 1 * (13 / 1000)


future::plan(future::multisession, workers = 2L)
# estimate season-specific index for each simulation draw 
for (i in seq_along(sp_vec)) {
  sim_tbl_sub <- sim_tbl %>% filter(species == sp_vec[i])
  sim_ind_list_summer <- furrr::future_map(
    sim_tbl_sub$sim_fit[1:100],
    function (x) {
      pp <- predict(x,
                    newdata = index_grid_hss %>%
                      filter(season_f == "su"),
                    se_fit = FALSE, re_form = NULL, return_tmb_object = TRUE)
      get_index(pp, area = sp_scalar, bias_correct = TRUE) %>%
        mutate(season_f = "su",
               species = sp_vec[i])
    }
  )
  saveRDS(
    sim_ind_list_summer ,
    here::here("data", "fits", "sim_fit",
               paste(sp_vec[i], "_summer_sim_index_final_mvrfrw.rds", sep = ""))
  )
  sim_ind_list_fall <- furrr::future_map(
    sim_tbl_sub$sim_fit[1:100],
    function (x) {
      pp <- predict(x, 
                    newdata = index_grid_hss %>%
                      filter(season_f == "wi"),
                    se_fit = FALSE, re_form = NULL, return_tmb_object = TRUE)
      get_index(pp, area = sp_scalar, bias_correct = TRUE) %>%
        mutate(season_f = "wi",
               species = sp_vec[i])
    }
  )
  saveRDS(
    sim_ind_list_fall ,
    here::here("data", "fits", "sim_fit",
               paste(sp_vec[i], "_fall_sim_index_final_mvrfrw.rds", sep = ""))
  )
}


# import saved indices from all_species_fit_season.R
# true_index_list <- readRDS(
#   here::here("data", "fits", "season_index_list_mvrfrw.rds")
# )

# true_index_summer <- furrr::future_map2(
#   all_fit_tbl$fit, all_fit_tbl$species,
#   function (x, y) {
#     pp <- predict(x, 
#                   newdata = index_grid_hss %>%
#                     filter(season_f == "su"),
#                   se_fit = FALSE, re_form = NULL, return_tmb_object = TRUE)
#     get_index(pp, area = sp_scalar, bias_correct = TRUE) %>%
#       mutate(season_f = "su",
#              species = y)
#   }
# )
# true_index_fall <- furrr::future_map2(
#   all_fit_tbl$fit, all_fit_tbl$species,
#   function (x, y) {
#     pp <- predict(x, 
#                   newdata = index_grid_hss %>%
#                     filter(season_f == "wi"),
#                   se_fit = FALSE, re_form = NULL, return_tmb_object = TRUE)
#     get_index(pp, area = sp_scalar, bias_correct = TRUE) %>%
#       mutate(season_f = "wi",
#              species = y)
#   }
# ) 

# true_ind_dat <- #true_index_list %>%
#   #bind_rows() %>% 
#   rbind(true_index_summer %>% bind_rows(), 
#         true_index_fall %>% bind_rows()) %>% 
#   mutate(
#     season = fct_recode(season_f, "summer" = "su", "fall" = "wi"),
#     survey = case_when(
#       season == "fall" & year %in% fall_years ~ "sampled",
#       season == "summer" & year %in% summer_years ~ "sampled",
#       TRUE ~ "no survey"
#     ),
#     log_lwr = log_est - (1.96 * se),
#     log_upr = log_est + (1.96 * se),
#     year_f = as.factor(year)
#   )
# 
# 
# sim_index_list_summer <- purrr::map(
#   sp_vec,
#   ~ readRDS(
#     here::here("data", "fits", "sim_fit",
#                paste(.x, "_summer_sim_index_final_mvrfrw.rds", sep = ""))
#   )
# )
# sim_index_list_fall <- purrr::map(
#   sp_vec,
#   ~ readRDS(
#     here::here("data", "fits", "sim_fit",
#                paste(.x, "_fall_sim_index_final_mvrfrw.rds", sep = ""))
#   ) 
# )

# n_iter <- length(sim_index_list_fall[[1]]) #how many sims per species?
# 
# sim_ind_dat <- tibble(
#   # species = c(rep(sp_vec, each = n_iter), rep(sp_vec, each = n_iter)),
#   iter = rep(seq(1, n_iter, by = 1), times = (length(sp_vec) * 2)),
#   sim_index = c(do.call(c, sim_index_list_summer), 
#                 do.call(c, sim_index_list_fall))
# ) %>%
#   unnest(cols = "sim_index") %>%
#   left_join(
#     ., 
#     true_ind_dat %>% 
#       select(species, year, year_f, season_f, true_log_est = log_est),
#     by = c("species", "year", "season_f")) %>% 
#   mutate(
#     season = fct_recode(season_f, "summer" = "su", "fall" = "wi"),
#     resid_est = true_log_est - log_est
#   )

# 
# png(here::here("figs", "ms_figs_season", "sim_index.png"), 
#     height = 8, width = 8, units = "in", res = 200)
# ggplot() +
#   geom_boxplot(data = sim_ind_dat,
#                aes(x = year_f, y = log_est)) +
#   geom_point(data = true_ind_dat %>% filter(species %in% sp_vec),
#              aes(x = year_f, y = log_est, colour = survey)) +
#   facet_grid(species~season, scales = "free_y") +
#   ggsidekick::theme_sleek() +
#   theme(legend.position = "top") +
#   scale_x_discrete(breaks = seq(2000, 2020, by = 5)) +
#   labs(y = "Log Estimated Abundance") +
#   theme(axis.title.x = element_blank())
# dev.off()
# 
# png(here::here("figs", "ms_figs_season", "resid_index.png"), 
#     height = 8, width = 8, units = "in", res = 200)
# ggplot() +
#   geom_boxplot(data = sim_ind_dat,
#                aes(x = year_f, y = resid_est)) +
#   geom_hline(yintercept = 0, lty = 2, colour = "red") +
#   facet_grid(species~season, scales = "free_y") +
#   ggsidekick::theme_sleek() +
#   theme(legend.position = "top") +
#   scale_x_discrete(breaks = seq(2000, 2020, by = 5)) +
#   labs(y = "Index Residuals") +
#   theme(axis.title.x = element_blank())
# dev.off()

