### Can fit parameters be recovered?
## Use simulated data generated by model in chinook_fit to determine whether key
## parameters can be reliably recovered.
## Sep 29, 2022
## Reran Oct 26: parameters recovered well for most species except range biased 
# high and headrope depth coefficients uncertain for chum in particular;
# consider rerunning with smooth for headrope, not cat. effects
## Reran Jan 31: "final" model after comparing spatiotemporal structures with
# cross validation
## Reran April 21: 


library(tidyverse)
library(sdmTMB)
library(ggplot2)

ncores <- parallel::detectCores() 
future::plan(future::multisession, workers = ncores - 3)


# fitted model from all_species_fit.R
fit_all_sp <- readRDS(
  here::here("data", "fits", "all_spatial_varying_new_scale.rds")) 
  

# simulate 20 MC draws from fitted models 
set.seed(456)
nsims = 20
sims_list <- purrr::map(
  fit_all_sp$fit, simulate, nsim = nsims#, re_form = ~0
)

# purrr::map2(sims_list, fit_all_sp$fit, sdmTMBextra::dharma_residuals)


## for each simulated dataset, refit model, recover pars and store

# make a tibble for each species simulations
sim_tbl <- purrr::pmap(
  list(fit_all_sp$species, fit_all_sp$fit, sims_list),
  function (sp, fits, x) {
    tibble(
      species = sp,
      iter = seq(1, nsims, by = 1),
      sim_dat = lapply(seq_len(ncol(x)), function(i) {
        # use fits instead of data in tibble because mismatched
        fits$data %>% 
          mutate(sim_catch = x[ , i])
      })
    )
  }
) %>% 
  bind_rows() %>% 
  left_join(., 
            fit_all_sp %>% select(species, fit), 
            by = c("species"))


## test w/ single model
dum <- sdmTMB(
  sim_catch ~ 0 + season_f  + day_night + survey_f + 
    scale_depth + scale_dist,
  # target_depth + dist_to_coast_km,
  offset = sim_tbl$sim_dat[[1]]$effort,
  data = sim_tbl$sim_dat[[1]],
  mesh =  fit_all_sp$fit[[1]]$spde,
  family = sdmTMB::nbinom2(),
  spatial = "off",
  spatiotemporal = "off",
  spatial_varying = ~ 0 + season_f + year_f,
  time_varying = ~ 1,
  time_varying_type = "rw0",
  time = "ys_index",
  extra_time = fit_all_sp$fit[[1]]$extra_time,
  share_range = TRUE,
  anisotropy = TRUE,
  control = sdmTMBcontrol(
    newton_loops = 1,
    map = list(
      # 1 per season, fix all years to same value
      ln_tau_Z = factor(
        c(1, 2, 3, 
          rep(4, times = length(unique(sim_tbl$sim_dat[[1]]$year)) - 1))
      )
    )
  ),
  silent = FALSE
)

# fit model to species (originally in parallel, but wouldn't run with furrr::)
sp_vec <- unique(sim_tbl$species)
for (i in 2:5) { #seq_along(sp_vec)) {
  sim_tbl_sub <- sim_tbl %>% filter(species == sp_vec[i])
  fit <- furrr::future_map2(
    sim_tbl_sub$sim_dat, sim_tbl_sub$fit, 
    function (x, fit) {
      sdmTMB(
        sim_catch ~ 0 + season_f  + day_night + survey_f + 
          scale_depth + scale_dist,
        # target_depth + dist_to_coast_km,
        offset = x$effort,
        data = x,
        mesh =  fit$spde,
        family = sdmTMB::nbinom2(),
        spatial = "off",
        spatiotemporal = "off",
        spatial_varying = ~ 0 + season_f + year_f,
        time_varying = ~ 1,
        time_varying_type = "rw0",
        time = "ys_index",
        extra_time = fit$extra_time,
        share_range = TRUE,
        anisotropy = TRUE,
        control = sdmTMBcontrol(
          newton_loops = 1,
          map = list(
            # 1 per season, fix all years to same value
            ln_tau_Z = factor(
              c(1, 2, 3, 
                rep(4, times = length(unique(x$year)) - 1))
            )
          )
        ),
        silent = FALSE
      )
    }
  )
  saveRDS(
    fit,
    here::here("data", "fits", "sim_fit", paste(sp_vec[i], ".rds", sep = ""))
  )
  }


# import saved sim fits 
sim_fit_list <- purrr::map(
  sp_vec,
  ~ readRDS(
    here::here("data", "fits", "sim_fit", paste(.x, ".rds", sep = ""))
  )
)

# some issues with b_j gradient (may need to drop dist to coast or std)
purrr::map(sim_fit_list[[5]], ~ sanity(.x))

sim_tbl$sim_fit <- do.call(c, sim_fit_list)


# extract fixed and ran effects pars from simulations
sim_tbl$pars <- purrr::map(
  sim_tbl$sim_fit, function (x) {
    fix <- tidy(x, effects = "fixed")
    ran <- tidy(x, effects = "ran_pars")
    rbind(fix, ran) 
  }
)

sim_pars <- sim_tbl %>% 
  select(species, iter, pars) %>% 
  unnest(cols = c(pars)) %>% 
  mutate(iter = as.factor(iter),
         species = abbreviate(species, minlength = 3)) 
saveRDS(sim_pars, here::here("data", "preds", "sim_pars.rds"))


# as above but for fitted models
fit_effs <- purrr::map2(
  sim_tbl$fit, sim_tbl$species, function (x, sp) {
    fix <- tidy(x, effects = "fixed")
    ran <- tidy(x, effects = "ran_pars")
    rbind(fix, ran) %>% 
      mutate(species = abbreviate(sp, minlength = 3)) 
  }
) %>% 
  bind_rows() 

sim_box <- ggplot() +
  geom_boxplot(data = sim_pars, aes(x = species, y = estimate)) +
  geom_point(data = fit_effs, aes(x = species, y = estimate), colour = "red") +
  facet_wrap(~term, scales = "free") +
  ggsidekick::theme_sleek()

png(here::here("figs", "ms_figs", "par_recovery_sim_box.png"), 
    height = 7, width = 11, units = "in", res = 250)
sim_box
dev.off()
